name: Update Website Daily

on:
  schedule:
    - cron: '*/10 * * * *' 

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest  # Replace with desired runner OS (if needed)
    steps:
      - uses: actions/checkout@v3  # Checkout your code

      - name: Switch to gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # Checkout gh-pages branch

      - name: Use Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Adjust if needed

      - name: Run update script
        run: python rss_app.py

      - name: Build Jekyll site (replace with actual command)
        run: bundle exec jekyll build  # Replace with your specific build command
       - name: Move files (replace with actual commands)
        run: |
          mv _site/* .
          rm -R _site/
env:
  # Add any environment variables needed by your build script (if applicable)

